gtema/openstack

Cargo.lock, openstack_cli/src/lib.rs, openstack_sdk/Cargo.toml, openstack_sdk/src/api/identity/v3/auth/token/create.rs, openstack_sdk/src/api/query.rs, openstack_sdk/src/api/rest_endpoint.rs, openstack_sdk/src/auth.rs, openstack_sdk/src/config.rs, openstack_sdk/src/openstack.rs, openstack_sdk/src/types/identity/v3.rs
Extend Auth to support MFA (totp)
=> feat(auth): add MFA auth support

.pre-commit-config.yaml, openstack_cli/src/compute/v2/server.rs
- chore: comment out unused (deprecated) mods
- chore(pre-commit): replace deprecated action
=> Reduce amount of warnings

Cargo.lock, Cargo.toml, openstack_sdk/Cargo.toml, openstack_sdk/src/api.rs, openstack_sdk/src/api/rest_endpoint.rs, openstack_sdk/src/auth.rs, openstack_sdk/src/config.rs, openstack_sdk/src/lib.rs, openstack_sdk/src/openstack.rs, openstack_sdk/src/utils.rs, openstack_sdk/src/websso.rs, openstack_sdk/static/callback.html
- **fix: ensure auth cache is enabled by default**
- **feat(auth): Enable WebSSO authentication**
=> Implement WebSSO auth

.github/dependabot.yml, .github/workflows/release-plz.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, xtask/Cargo.toml
- **chore: add CI workflows**
- **chore: update cargo.lock**
=> improve project release CI/CD

Cargo.lock, release-plz.toml, xtask/Cargo.toml
- **chore: add release-plz config**
- **updates to config files**
=> chore: update release-plz

Cargo.lock, openstack_cli/Cargo.toml, openstack_cli/src/lib.rs, openstack_sdk/CHANGELOG.md, openstack_sdk/Cargo.toml, openstack_sdk/src/lib.rs, structable_derive/CHANGELOG.md, structable_derive/Cargo.toml
- **chore: Prepare release of sdk and strucable_derive**
=> chore: release sdk and structable_derive

.github/workflows/release-plz.yml, .github/workflows/release.yml, Cargo.toml
- **chore(cd): convert release-plz to be GH app**
=> chore(cd): improve cd configuration

openstack_sdk/src/api/paged.rs, openstack_sdk/src/api/paged/iter.rs, openstack_sdk/src/api/paged/next_page.rs, openstack_sdk/src/api/paged/pagination.rs
- **fix: Respect headers passed into the `api` command**
- **fix: Respect server defaults for pagination**
=> fix: Respect server page size

openstack_sdk/src/catalog.rs
When service is missing completely in the catalog setting endpoint
override has no effect. This is not what is desired, so change it to be
used as a fallback when nothing is found in known endpoints.
=> fix: respect endpoint_override for missing catalog entry

openstack_cli/src/block_storage/v3/volume/os_force_detach.rs, openstack_cli/src/block_storage/v3/volume/os_terminate_connection.rs, openstack_cli/src/network/v2/router/add_router_interface.rs, openstack_cli/src/network/v2/router/remove_router_interface.rs, openstack_sdk/src/api/network/v2/router/add_router_interface.rs, openstack_sdk/src/api/network/v2/router/remove_router_interface.rs
- **chore: sort struct fields alphabetically**
- **chore: remove another unnecessary cloning operation**
- **feat: implement router {add,remove}_router_interface**
=> feat: extend network.router

._typos.toml, _typos.toml
Add "ro" as an exception into the typos
=> chore(typos): add typos exception

.github/workflows/functional.yml
Add functional testing based on devstack
=> chore(ci): add functional test workflow

.github/workflows/release.yml, Cargo.toml
=> feat: Update cargo-dist version

.github/workflows/audit.yml, .github/workflows/cache-clean.yml, .github/workflows/committed.yml, .github/workflows/functional.yml, .github/workflows/linters.yml, .github/workflows/mdbook.yml, .github/workflows/release-plz.yml, .github/workflows/rust.yml, .github/workflows/scorecard.yml, .pre-commit-config.yaml
Signed-off-by: StepSecurity Bot <bot@stepsecurity.io>
=> chore(ci): Apply security best practices

Cargo.lock, Cargo.toml, openstack_sdk/Cargo.toml
- **chore(deps): Update bytes to 1.6**
- **chore(ci): Update dependency lock**
=> chore(ci): Update dependencies

Cargo.lock, Cargo.toml, fuzz/.gitignore, fuzz/Cargo.toml, fuzz/fuzz_targets/fuzz_openstack_sdk_config.rs, fuzz/rust-toolchain.toml, openstack_sdk/Cargo.toml
Add fuzz with first test of openstack_sdk config.
=> chore(qa): Initialize fuzzing

openstack_sdk/src/catalog.rs
Treat endpoint overrides as 'Endpoint' structure.
=> feat(sdk): Use 'Endpoint' struct for endpoint overrides

.github/workflows/ci.yml, fuzz/Cargo.toml
Enable fuzz tests in the CI jobs
=> chore(tests): Enable fuzz tests

openstack_cli/src/lib.rs, openstack_sdk/src/error.rs, openstack_sdk/src/openstack.rs, openstack_sdk/src/openstack_async.rs
Attempt to auth to not properly working Keystone throws a discovery
error. This is not very helpful on it's own so let's improve the
message.
=> chore(error): Improve discovery error

.github/workflows/ci.yml, .github/workflows/release.yml, Cargo.toml, fuzz/Cargo.toml
Add cargo dist back again with certain changes in the configuration. The
project is slowly evolving and getting new features, so it definitely
make sense to keep an eye on it and rely on it's usability.
=> chore(ci): Re-add cargo dist

.github/workflows/release.yml, CONTRIBUTING.md, Cargo.toml
Update cargo-dist and adopt changes in ci file (keeping also local
changes).
=> chore(ci): Update cargo-dist to 0.16.0

.github/workflows/release.yml
Without tag names it is hard to review renovate PRs just changing commit hash.
=> chore(ci): Add explicit action tag names

.github/renovate.json5
=> chore(ci): Create renovate.json5

.github/renovate.json5
=> chore(ci): Revert: Create renovate.json5

openstack_cli/src/api/mod.rs
Response of the `osc api` command can be json, empty json or not json at
all. `HEAD` or `DELETE` opertaion tend not to return json or return a
json with empty body. In order to avoid throwing deserialization error
check that:
- content-type is application/json
- !body.is_empty()
=> fix(openstack_cli): Check `osc api` response before deserializing

.dockerignore, .github/workflows/container-build.yml, .github/workflows/container-publish.yml, Dockerfile
Start building container (based on alpine) with osc inside to allow osc
usage in K8.
=> feat(ci): Build container with osc

.github/workflows/container-build.yml, .github/workflows/container-publish.yml, Dockerfile
add labels to container image and address some scorecard complains.
=> chore(ci): Address image build scorecard hints

openstack_cli/src/compute/v2/server/tag.rs, openstack_sdk/README.md, openstack_sdk/src/api.rs, openstack_sdk/src/api/rest_endpoint.rs, openstack_sdk/src/catalog/service_authority.rs
Newest rust version reports new issues. Address some of them that are
not in the generated code.
=> chore: Address some warning of newest rust

openstack_cli/src/network/v2/default_security_group_rule/create.rs, openstack_cli/src/network/v2/default_security_group_rule/list.rs, openstack_cli/src/network/v2/default_security_group_rule/set.rs, openstack_cli/src/network/v2/default_security_group_rule/show.rs, openstack_cli/src/network/v2/security_group/create.rs, openstack_cli/src/network/v2/security_group/list.rs, openstack_cli/src/network/v2/security_group/set.rs, openstack_cli/src/network/v2/security_group/show.rs, openstack_cli/src/network/v2/security_group_rule/create.rs, openstack_cli/src/network/v2/security_group_rule/list.rs, openstack_cli/src/network/v2/security_group_rule/set.rs, openstack_cli/src/network/v2/security_group_rule/show.rs, openstack_sdk/src/api/network/v2/default_security_group_rule/create.rs, openstack_sdk/src/api/network/v2/default_security_group_rule/list.rs, openstack_sdk/src/api/network/v2/security_group_rule/create.rs, openstack_sdk/src/api/network/v2/security_group_rule/list.rs
Regenerated code from the codegenerator.
=> fix: Fix certain network.SG properties

.github/workflows/ci.yml, .github/workflows/container-build.yml, .github/workflows/functional.yml, .github/workflows/linters.yml, .github/workflows/release.yml
try be more precise in where the job should run.
=> Adapt workflows filters

Cargo.lock, Cargo.toml, openstack_cli/Cargo.toml, openstack_cli/src/bin/osc.rs
The rust-cli WG has a crate that is also recommended by the ratatui for
making crash reports more human friendly. Start using it.
=> feat: Introduce use of human-panic

doc/src/osc.md, openstack_cli/src/network/v2/subnetpool.rs, openstack_cli/tests/network/v2/subnetpool/mod.rs
Enable `add_prefixes` and `remove_prefixes` of the subnetpool resource.
=> feat: Activate net.subnetpool.XXX_prefixes commands

openstack_sdk/src/config.rs
Implement method to list all available connections in the clouds.yaml.
This is going to be used in the TUI and can be potentially also helpful
in the cli.
=> feat: Add list of available connections

Cargo.lock, Cargo.toml, doc/src/osc.md, openstack_cli/Cargo.toml, openstack_cli/README.md, openstack_cli/src/cli.rs, openstack_cli/src/lib.rs
add command to generate shell autocompletion file.
=> feat(cli): Enable shell autocompletion

.github/workflows/release-plz.yml, release-plz.toml
- add openstack_tui to be managed by release_plz
- rework release-plz workflow to produce individual PRs for packages
=> chore(ci): Add openstack_tui into the release-plz

Cargo.lock, openstack_tui/Cargo.toml
=> chore: Update dependencies

openstack_cli/src/error.rs
Further improvements in the codegenerator require new exceptions to be
added.
=> feat: Add few exceptions for cli

openstack_cli/src/lib.rs
The change addresses panic when neither `--os-cloud` not env are being
used (it used to do `expect`). In addition to that add a warning when
`--os-cloud` is used with mixing `--os-XXX` vars to warn user of
potential undesired behavior.
=> feat: Remove few panics in auth handling

openstack_tui/src/components/compute/flavors.rs, openstack_tui/src/components/compute/servers.rs, openstack_tui/src/components/describe.rs, openstack_tui/src/components/image/images.rs, openstack_tui/src/components/network/networks.rs, openstack_tui/src/components/network/subnets.rs, openstack_tui/src/components/table_view.rs
Reuse Describe component directly in the table view to avoid code
duplication.
=> feat(tui): De-duplicate describe view

openstack_tui/src/app.rs, openstack_tui/src/components/cloud_select_popup.rs, openstack_tui/src/components/describe.rs, openstack_tui/src/components/error_popup.rs, openstack_tui/src/components/home.rs, openstack_tui/src/components/resource_select_popup.rs, openstack_tui/src/components/table_view.rs, openstack_tui/src/config.rs, openstack_tui/src/utils.rs
Centralize UI color styling into one struct part of the config.
=> feat: Add styling support

.github/workflows/container-publish.yml
When making release container publishing job should work on openstack_cli-vX.Y.Z. tag
=> Update container build on release

openstack_tui/src/cloud_services.rs, openstack_tui/src/cloud_services/compute.rs, openstack_tui/src/cloud_services/image.rs, openstack_tui/src/cloud_services/network.rs, openstack_tui/src/cloud_worker.rs, openstack_tui/src/main.rs
Structure service based cloud methods into dedicated traits to keep code
smaller.
=> feat: Separate service methods into traits

Dockerfile, openstack_sdk/Cargo.toml, openstack_sdk/README.md, openstack_sdk/examples/ignore.rs, openstack_sdk/examples/paged.rs, openstack_sdk/examples/query.rs, openstack_sdk/examples/query_find.rs, openstack_sdk/src/api.rs
- add basic interface description
- add crate examples demonstrating primitive usage
=> feat: Improve crate (interface) documentation

Cargo.lock, Cargo.toml, README.md, openstack_cli/Cargo.toml
- update dependencies
- update links to latest release installers
=> chore: Update locked dependencies

openstack_sdk/src/api/find.rs
Some services (i.e. DNS) return 400 for `/v2/zones/test.com.` instead of
404. Since there are generaly some occurences of that across OpenStack
process this error same as 404 and go into listing.
=> fix: Address find when GET return 400

Cargo.lock, openstack_tui/Cargo.toml, openstack_tui/src/components/describe.rs, openstack_tui/src/components/table_view.rs
=> chore: Update ratatui version

openstack_cli/src/bin/osc.rs
Exclude some known errors not to trigger 'report issue' (server error,
config error)
=> fix: Exclude some errors from 'report issue'

openstack_cli/src/load_balancer/v2/loadbalancer/create.rs, openstack_cli/src/network/v2/address_group/add_addresses.rs, openstack_cli/src/network/v2/address_group/create.rs, openstack_cli/src/network/v2/address_group/list.rs, openstack_cli/src/network/v2/address_group/remove_addresses.rs, openstack_cli/src/network/v2/address_group/set.rs, openstack_cli/src/network/v2/address_group/show.rs, openstack_sdk/src/api/network/v2/address_group/list.rs
Change-Id: If1d9a47a9a87c985988b3378cddf0330d14b9458
Changes are triggered by https://review.opendev.org/928664
=> feat: Incorporate updated network schemas

openstack_cli/src/dns/v2/zone/share/list.rs, openstack_cli/src/placement/v1.rs
There is nothing much useful, just a synchronization to reduce diff in
next changes.
Change-Id: I3c70e58e341be186cca03360e1e47205a77901f8
Changes are triggered by https://review.opendev.org/934236
=> fix: New generated content

openstack_cli/src/identity/v3/group.rs, openstack_cli/src/identity/v3/group/user.rs, openstack_cli/src/identity/v3/group/user/delete.rs, openstack_cli/src/identity/v3/group/user/set.rs, openstack_cli/src/identity/v3/group/user/show.rs, openstack_cli/tests/identity/v3/group/user/mod.rs
Add commands to manage group<user relationships
=> feat: Add identity.group.user commands

Cargo.lock, Cargo.toml, openstack_cli/Cargo.toml, openstack_sdk/Cargo.toml
use `feat` this time because thiserror has a major upgrade
=> feat: Update dependencies

openstack_cli/README.md, openstack_cli/src/cli.rs, openstack_cli/src/lib.rs, openstack_cli/src/tracing_stats.rs, openstack_sdk/src/api/rest_endpoint.rs, openstack_sdk/src/auth.rs, openstack_sdk/src/config.rs, openstack_sdk/src/openstack.rs, openstack_sdk/src/openstack_async.rs, openstack_sdk/src/types.rs
Add argument enabling recording all HTTP requests and printing grouped
timing to the stderr.
=> feat: add `--timing` argument

openstack_tui/src/app.rs, openstack_tui/src/cloud_worker.rs, openstack_tui/src/cloud_worker/network.rs, openstack_tui/src/cloud_worker/types.rs, openstack_tui/src/components/home.rs
- add few network quota details
- do not show error popup when quotas cannot be fetched, instead hide
the data
=> feat: Add network quota

openstack_tui/.config/config.json5, openstack_tui/src/app.rs, openstack_tui/src/components/compute/flavors.rs, openstack_tui/src/components/compute/servers.rs, openstack_tui/src/components/fuzzy_select_list.rs, openstack_tui/src/components/header.rs, openstack_tui/src/components/identity/projects.rs, openstack_tui/src/components/image/images.rs, openstack_tui/src/components/network/networks.rs, openstack_tui/src/components/network/subnets.rs, openstack_tui/src/components/project_select_popup.rs, openstack_tui/src/components/resource_select_popup.rs, openstack_tui/src/components/table_view.rs
- further de-duplicate code for components
- ensure "refresh" event is only handeled by current active component
- truncate values in first header column adding ".." suffix at the end
indicating the value was shortened. Also increase default column
width to a reasonable value.
=> feat: Minor improvements

openstack_tui/.config/config.json5, openstack_tui/src/action.rs, openstack_tui/src/app.rs, openstack_tui/src/cloud_worker/identity.rs, openstack_tui/src/cloud_worker/identity/types.rs, openstack_tui/src/cloud_worker/types.rs, openstack_tui/src/components/identity.rs, openstack_tui/src/components/identity/application_credentials.rs, openstack_tui/src/components/identity/users.rs, openstack_tui/src/components/resource_select_popup.rs, openstack_tui/src/mode.rs
List user application credentials
=> feat: Add application credentials mode

openstack_tui/.config/config.json5, openstack_tui/src/action.rs, openstack_tui/src/cloud_worker.rs, openstack_tui/src/cloud_worker/compute.rs, openstack_tui/src/cloud_worker/identity.rs, openstack_tui/src/cloud_worker/image.rs, openstack_tui/src/cloud_worker/network.rs, openstack_tui/src/components/compute/servers.rs, openstack_tui/src/components/identity/application_credentials.rs, openstack_tui/src/components/identity/group_users.rs, openstack_tui/src/components/identity/groups.rs, openstack_tui/src/components/identity/users.rs, openstack_tui/src/components/image/images.rs, openstack_tui/src/components/network/networks.rs, openstack_tui/src/components/network/security_group_rules.rs, openstack_tui/src/components/network/security_groups.rs, openstack_tui/src/components/network/subnets.rs, openstack_tui/src/mode.rs
give more reasonable acition names
=> chore: Improve action names

openstack_tui/src/cloud_worker/network/types.rs
Finally request sorting by multiple columns from neutron directly
=> feat: Better sort security group rules

openstack_tui/.config/config.json5, openstack_tui/src/app.rs, openstack_tui/src/cloud_worker.rs, openstack_tui/src/cloud_worker/block_storage.rs, openstack_tui/src/cloud_worker/block_storage/types.rs, openstack_tui/src/cloud_worker/types.rs, openstack_tui/src/components.rs, openstack_tui/src/components/block_storage.rs, openstack_tui/src/components/block_storage/backups.rs, openstack_tui/src/components/block_storage/snapshots.rs, openstack_tui/src/components/block_storage/volumes.rs, openstack_tui/src/mode.rs
- backups
- snapshots
- volumes
so far without any relations
=> feat: Add few volume views

openstack_tui/.config/config.json5, openstack_tui/src/action.rs, openstack_tui/src/app.rs, openstack_tui/src/cloud_worker/compute.rs, openstack_tui/src/cloud_worker/compute/types.rs, openstack_tui/src/cloud_worker/types.rs, openstack_tui/src/components/compute.rs, openstack_tui/src/components/compute/server_instance_action_events.rs, openstack_tui/src/components/compute/server_instance_actions.rs, openstack_tui/src/mode.rs
add possibility to visualize instance actions and associated events of a
server.
=> feat: Add server instance_actions view

openstack_tui/src/app.rs
When a popup is open and we try to type something in there is a chance
to collide with shortcuts of the mode underneath the popup. Do not
try to convert key events to actions when popup is open
=> fix: Prevent actions when popup is open

openstack_tui/src/components/header.rs
rework header component to handle as many mode keybindings as there are.
Collect all possible data as early as possible to reduce amount of
operations during rendering.
=> chore: Update the header component

doc/src/tui/compute/flavors.md, openstack_tui/.config/config.json5, openstack_tui/src/action.rs, openstack_tui/src/cloud_worker/compute/types.rs, openstack_tui/src/components/compute/flavors.rs, openstack_tui/src/components/compute/servers.rs
`<s>` in flavors lists all servers provisioned with this flavor.
=> feat: Enable listing servers of flavor

openstack_tui/.config/config.json5, openstack_tui/src/action.rs, openstack_tui/src/app.rs, openstack_tui/src/components/block_storage/backups.rs, openstack_tui/src/components/block_storage/snapshots.rs, openstack_tui/src/components/block_storage/volumes.rs, openstack_tui/src/components/compute/aggregates.rs, openstack_tui/src/components/compute/flavors.rs, openstack_tui/src/components/compute/hypervisors.rs, openstack_tui/src/components/compute/server_instance_action_events.rs, openstack_tui/src/components/compute/server_instance_actions.rs, openstack_tui/src/components/compute/servers.rs, openstack_tui/src/components/header.rs, openstack_tui/src/components/home.rs, openstack_tui/src/components/identity/application_credentials.rs, openstack_tui/src/components/identity/group_users.rs, openstack_tui/src/components/identity/groups.rs, openstack_tui/src/components/identity/projects.rs, openstack_tui/src/components/identity/users.rs, openstack_tui/src/components/image/images.rs, openstack_tui/src/components/network/networks.rs, openstack_tui/src/components/network/routers.rs, openstack_tui/src/components/network/security_group_rules.rs, openstack_tui/src/components/network/security_groups.rs, openstack_tui/src/components/network/subnets.rs, openstack_tui/src/components/resource_select_popup.rs, openstack_tui/src/components/table_view.rs
replace a single prev_mode with proper stack tracing mode changes with
possibility to switch to the new mode pushing change onto the stack and
not.
=> fix: Ensure esc properly work on deep stacks

openstack_tui/src/app.rs, openstack_tui/src/components/cloud_select_popup.rs, openstack_tui/src/components/confirm_popup.rs, openstack_tui/src/components/error_popup.rs, openstack_tui/src/components/header.rs, openstack_tui/src/components/project_select_popup.rs, openstack_tui/src/components/resource_select_popup.rs, openstack_tui/src/components/table_view.rs, openstack_tui/src/utils.rs
- switch to fixed size of popups
- disable header when height <=30
- disable describe pane when width <= 140
=> fix: Improve responsiveness

openstack_tui/src/cloud_worker/load_balancer.rs, openstack_tui/src/cloud_worker/load_balancer/types.rs
We need to adapt the code slightly to allow successful compilation with
the update query parameters in octavia service resources.
=> chore: Prepare for octavia filters

.github/workflows/linters.yml, openstack_cli/src/load_balancer/v2/pool/member.rs, openstack_cli/src/tracing_stats.rs, openstack_sdk/src/api.rs, openstack_sdk/src/catalog/discovery.rs, openstack_sdk/src/catalog/service_endpoint.rs, openstack_sdk/src/config.rs, openstack_tui/Cargo.toml
- address some clippy warnings
- raise tui msrv as required by the code
- split clippy workflow to use different checks for sdk/cli and tui
=> chore: Address clippy complains

openstack_cli/src/identity/v3/user/create.rs, openstack_cli/src/identity/v3/user/set.rs
Address https://rust-lang.github.io/rust-clippy/master/index.html#single_char_pattern
Change-Id: If9868e827a03890bf81808565a9eca3cb72f5516
Changes are triggered by https://review.opendev.org/936629
=> chore: Use single quotes for single char

openstack_cli/src/dns/v2/zone/share/list.rs, openstack_cli/src/load_balancer/v2/amphorae/list.rs, openstack_cli/src/load_balancer/v2/availability_zone/list.rs, openstack_cli/src/load_balancer/v2/availability_zone_profile/list.rs, openstack_cli/src/load_balancer/v2/flavor/list.rs, openstack_cli/src/load_balancer/v2/flavor_profile/list.rs, openstack_cli/src/load_balancer/v2/healthmonitor/list.rs, openstack_cli/src/load_balancer/v2/l7policy/list.rs, openstack_cli/src/load_balancer/v2/l7policy/rule/list.rs, openstack_cli/src/load_balancer/v2/listener/list.rs, openstack_cli/src/load_balancer/v2/loadbalancer/list.rs, openstack_cli/src/load_balancer/v2/pool/list.rs, openstack_cli/src/load_balancer/v2/pool/member/list.rs, openstack_cli/src/load_balancer/v2/provider/list.rs, openstack_sdk/src/api/load_balancer/v2/amphorae/list.rs, openstack_sdk/src/api/load_balancer/v2/availability_zone/list.rs, openstack_sdk/src/api/load_balancer/v2/availability_zone_profile/list.rs, openstack_sdk/src/api/load_balancer/v2/flavor/list.rs, openstack_sdk/src/api/load_balancer/v2/flavor_profile/list.rs, openstack_sdk/src/api/load_balancer/v2/healthmonitor/list.rs, openstack_sdk/src/api/load_balancer/v2/l7policy/list.rs, openstack_sdk/src/api/load_balancer/v2/l7policy/rule/list.rs, openstack_sdk/src/api/load_balancer/v2/listener/list.rs, openstack_sdk/src/api/load_balancer/v2/loadbalancer/list.rs, openstack_sdk/src/api/load_balancer/v2/pool/list.rs, openstack_sdk/src/api/load_balancer/v2/pool/member/list.rs, openstack_sdk/src/api/load_balancer/v2/provider/list.rs
- add limit/marker/page_reverse
- sort QP alphabetically
Change-Id: I9c8c3e73b8b81827fa26b51ae65337ce93ab5840
Changes are triggered by https://review.opendev.org/936763
=> feat: Add pagination QP to octavia resources

openstack_tui/src/main.rs
Allow clippy to correct the code.
=> chore: Remove deny unused in tui

openstack_cli/src/load_balancer/v2/loadbalancer/create.rs, openstack_cli/src/load_balancer/v2/pool/member/create.rs, openstack_cli/src/load_balancer/v2/pool/member/list.rs, openstack_cli/src/load_balancer/v2/pool/member/replace.rs, openstack_cli/src/load_balancer/v2/pool/member/set.rs, openstack_cli/src/load_balancer/v2/pool/member/show.rs, openstack_sdk/src/api/load_balancer/v2/listener/create.rs, openstack_sdk/src/api/load_balancer/v2/loadbalancer/create.rs, openstack_sdk/src/api/load_balancer/v2/pool/create.rs, openstack_sdk/src/api/load_balancer/v2/pool/member/create.rs, openstack_sdk/src/api/load_balancer/v2/pool/member/replace.rs, openstack_tui/src/cloud_worker/load_balancer/v2/pool/member/list.rs
Hardcode barbican quota schemas. There are also octavia changes coming in.
Change-Id: Ida732b73f62ab5623edd8af571390debcf67facf
Changes are triggered by https://review.opendev.org/941543
=> feat: New generated content

deny.toml
Waiting for the deps to update
=> chore: Skip RUSTSEC-2024-0436

typos.toml
Some(typ) is what we want it to be
=> chore: Add typos skip

openstack_cli/src/cli.rs, openstack_cli/src/container_infrastructure_management/v1.rs, openstack_cli/src/container_infrastructure_management/v1/certificate.rs, openstack_cli/src/container_infrastructure_management/v1/cluster.rs, openstack_cli/src/container_infrastructure_management/v1/cluster/nodegroup.rs, openstack_cli/src/container_infrastructure_management/v1/clustertemplate.rs, openstack_cli/src/container_infrastructure_management/v1/federation.rs, openstack_cli/src/container_infrastructure_management/v1/mservice.rs, openstack_cli/src/container_infrastructure_management/v1/quota.rs, openstack_cli/src/container_infrastructure_management/v1/stat.rs, openstack_cli/src/container_infrastructure_management/v1/version.rs, openstack_cli/src/lib.rs, openstack_cli/tests/container_infrastructure_management/mod.rs, openstack_cli/tests/container_infrastructure_management/v1/certificate/mod.rs, openstack_cli/tests/container_infrastructure_management/v1/cluster/mod.rs, openstack_cli/tests/container_infrastructure_management/v1/cluster/nodegroup/mod.rs, openstack_cli/tests/container_infrastructure_management/v1/clustertemplate/mod.rs, openstack_cli/tests/container_infrastructure_management/v1/federation/mod.rs, openstack_cli/tests/container_infrastructure_management/v1/mod.rs, openstack_cli/tests/container_infrastructure_management/v1/mservice/mod.rs, openstack_cli/tests/container_infrastructure_management/v1/quota/mod.rs, openstack_cli/tests/container_infrastructure_management/v1/stat/mod.rs, openstack_cli/tests/container_infrastructure_management/v1/version/mod.rs
Certain commands are currently not covered since they require fixes on the
codegenerator side.
=> feat: Enable majority of magnum commands in cli

openstack_cli/src/identity/v3/os_federation/identity_provider/protocol/create.rs, openstack_cli/src/identity/v3/os_federation/identity_provider/protocol/set.rs, openstack_sdk/src/api/identity/v3/os_federation/identity_provider/protocol/create.rs, openstack_sdk/src/api/identity/v3/os_federation/identity_provider/protocol/set.rs
Temporary hardcode protocol schema which is about to be replaced with a proper
schema.
Change-Id: Iba6eff82645b18c788d6664e2fbc7f0e3d4244f7
Changes are triggered by https://review.opendev.org/945020
=> feat: Replace imported protocol schema

doc/src/tui/config.md, openstack_tui/.config/config.yaml, openstack_tui/src/components/block_storage/backups.rs, openstack_tui/src/components/block_storage/snapshots.rs, openstack_tui/src/components/block_storage/volumes.rs, openstack_tui/src/components/compute/aggregates.rs, openstack_tui/src/components/compute/flavors.rs, openstack_tui/src/components/compute/hypervisors.rs, openstack_tui/src/components/compute/server_instance_action_events.rs, openstack_tui/src/components/compute/server_instance_actions.rs, openstack_tui/src/components/compute/servers.rs, openstack_tui/src/components/dns/recordsets.rs, openstack_tui/src/components/dns/zones.rs, openstack_tui/src/components/identity/application_credentials.rs, openstack_tui/src/components/identity/group_users.rs, openstack_tui/src/components/identity/groups.rs, openstack_tui/src/components/identity/projects.rs, openstack_tui/src/components/identity/users.rs, openstack_tui/src/components/image/images.rs, openstack_tui/src/components/load_balancer/health_monitors.rs, openstack_tui/src/components/load_balancer/listeners.rs, openstack_tui/src/components/load_balancer/loadbalancers.rs, openstack_tui/src/components/load_balancer/pool_members.rs, openstack_tui/src/components/load_balancer/pools.rs, openstack_tui/src/components/network/networks.rs, openstack_tui/src/components/network/routers.rs, openstack_tui/src/components/network/security_group_rules.rs, openstack_tui/src/components/network/security_groups.rs, openstack_tui/src/components/network/subnets.rs
Drop manually created resource structures in favor of autogenerated ones.
With this we can also enable view configuration.
=> feat: Switch to generated response structs

openstack_cli/src/identity/v3/user/password/set.rs, openstack_sdk/src/api/identity/v3/auth/os_federation/saml2/create.rs, openstack_sdk/src/api/identity/v3/auth/os_federation/saml2/ecp/create.rs, openstack_sdk/src/api/identity/v3/auth/token/create.rs, openstack_sdk/src/api/identity/v3/user/password/set.rs
Enable sensitive handling of certain fields known to contain sensitive data
(password, passcode, secret, token.id)
Change-Id: Iae8cf9a084b981600fc0b1b94176c0ef4109c5df
Changes are triggered by https://review.opendev.org/945425
=> feat: Make sensitive fields be SecretString

openstack_tui/src/components/table_view.rs
wrap json conversion error with the failing json. It may produce huge result
forcing us to do something else, but not having this data is more confusing.
=> feat: Add original json data to the error

openstack_tui/.config/config.yaml, openstack_tui/src/components/compute/server_instance_action_events.rs, openstack_tui/src/components/compute/server_instance_actions.rs, openstack_types/src/compute/v2/server/instance_action/response/get.rs, openstack_types/src/compute/v2/server/instance_action/response/list.rs
Change-Id: I5912a18f1a7f60b6eff96aeb9580eb2d05c3ebb6
Changes are triggered by https://review.opendev.org/947667
=> feat: Add instance_uuid to the instance action schema

Cargo.lock, Cargo.toml, openstack_sdk/Cargo.toml, openstack_tui/Cargo.toml, openstack_tui/src/action.rs, openstack_tui/src/app.rs, openstack_tui/src/cloud_worker.rs, openstack_tui/src/components/error_popup.rs, openstack_tui/src/components/home.rs, openstack_tui/src/components/table_view.rs, openstack_tui/src/error.rs
Rework error handling so that if we get a json serde error the error
popup offers to report the issue (open browser with pre-populated info
and prepared crash information file).
=> feat: Add basic error reporting helper

.github/workflows/mdbook.yml, README.md, doc/book.toml, doc/src/SUMMARY.md, doc/src/cli.md, doc/src/cli/config.md, doc/src/cli/interface.md, doc/theme/index.hbs, openstack_cli/.config/config.yaml, openstack_cli/README.md, openstack_cli/src/cli.rs, openstack_cli/src/config.rs, openstack_cli/src/object_store/v1/container/create.rs, openstack_cli/src/object_store/v1/container/list.rs, openstack_cli/src/object_store/v1/container/prune.rs, openstack_cli/src/object_store/v1/container/set.rs, openstack_cli/src/object_store/v1/container/show.rs, openstack_cli/src/object_store/v1/object/download.rs, openstack_cli/src/object_store/v1/object/list.rs, openstack_cli/src/object_store/v1/object/show.rs, openstack_cli/src/object_store/v1/object/upload.rs
Adapt default cli configuration for the resources output. Add some
documentation on how this can be used.
=> feat: Update default cli output configuration

openstack_cli/README.md
=> chore: Address linter comments

openstack_cli/src/identity/v3/auth/os_federation/saml2/create.rs, openstack_cli/src/identity/v3/auth/os_federation/saml2/ecp/create.rs, openstack_cli/src/identity/v3/auth/token/create.rs, openstack_sdk/src/api/identity/v3/auth/os_federation/saml2/create.rs, openstack_sdk/src/api/identity/v3/auth/os_federation/saml2/ecp/create.rs, openstack_sdk/src/api/identity/v3/auth/token/create.rs, openstack_types/src/block_storage.rs, openstack_types/src/compute.rs, openstack_types/src/container_infrastructure_management.rs, openstack_types/src/dns.rs, openstack_types/src/identity.rs, openstack_types/src/image.rs, openstack_types/src/load_balancer.rs, openstack_types/src/network.rs, openstack_types/src/object_store.rs, openstack_types/src/placement.rs
Change-Id: I652e8b85632789d5172593154ddd9fef7508f359
Changes are triggered by https://review.opendev.org/948845
=> chore: Fix typos in parameter names

openstack_cli/src/load_balancer/v2/loadbalancer/delete.rs, openstack_sdk/src/api/load_balancer/v2/loadbalancer/delete.rs, openstack_tui/src/cloud_worker/load_balancer/v2/loadbalancer/delete.rs, openstack_types/data/load-balancer/v2.27.yaml, openstack_types/data/load-balancer/v2.yaml
Change-Id: I8f394639f3272d4385618dda6731880e02e85a4e
Changes are triggered by https://review.opendev.org/948906
=> feat: Add cascade QP for delete octavia loadbalancer

openstack_types/data/network/v2.26.yaml, openstack_types/data/network/v2.yaml
On the response admin_state_up can be only boolean
Change-Id: I2d991491dbc5a97e36446a6d29c52b653b5a1657
Changes are triggered by https://review.opendev.org/949133
=> fix: Adjust fip.port_details schema

doc/src/cli/config.md, openstack_cli/.config/config.yaml, openstack_cli/src/config.rs, openstack_cli/src/object_store/v1/object/list.rs, openstack_cli/src/output.rs
Implement column constraints setting min/fixed/max width of the column
```yaml
views:
dns/zone:
default_fields: [id, name]
fields:
- name: id
width: 38
```
=> feat: Add output column constraints

openstack_cli/.config/config.yaml, openstack_cli/src/output.rs
Add hints on how to see router interfaces and prune object-store
container.
=> chore: Add first command hints

openstack_cli/src/compute/v2/quota_set.rs, openstack_cli/tests/compute/v2/quota_set/mod.rs, openstack_tui/src/components/identity/users.rs
shortly we are going to have an update of certain schemas and it
currently is failing build. Comment use of certain fields out to enable
us landing this update.
=> chore: Prepare update of identity schemas

.github/workflows/release.yml, dist-workspace.toml
repair skip of auditable for arm64-linux
=> Repair use of cargo-auditable for arm64-linux

openstack_types/data/identity/keystone_rust.yaml
Also ensure new features are activated when running clippy.
Change-Id: I95d5814ff0691ac859eff8435a8c155acf0559ed
Changes are triggered by https://review.opendev.org/961395
=> chore: Add keystone-ng idp and mapping resources metadata
