gtema/openstack

- doc/src/osc.md
- openstack_cli/src/auth/login.rs
- openstack_cli/src/auth/mod.rs
- openstack_cli/src/lib.rs
- openstack_sdk/src/openstack.rs
- openstack_sdk/src/state.rs
- openstack_sdk/src/types/identity/v3.rs
Implement basic `osc auth login` command that ensures there is cloud
connection and writes token to the stdout. It is instended that this
invokes different session creation path in the SDK that allows
interactive mode.
> feat(auth): implement stub `osc auth login` command

- doc/src/osc.md
- openstack_cli/src/api/mod.rs
- openstack_cli/src/error.rs
`api` command declared support for additional headers to be sent with
the request, but it actually ignored them. Fix that making it possible
to set microversion header.
Add `-H` alias to the headers making it close to that of `curl`.
> fix: Respect headers passed into the `api` command

- Cargo.lock
- Cargo.toml
- openstack_cli/Cargo.toml
- openstack_sdk/Cargo.toml
- structable_derive/Cargo.toml
- xtask/Cargo.toml
switch to the caret requirement syntax that allows normal semver updates
from the tilde.
> chore: switch to caret requirements syntax

- README.md
remote "prompt" from console code snippet in the readme to ease copying
> chore: remove prompt from console snippet

- README.md
replace the link to download `osc` installer to use automatically the
latest version.
> fix: change download link to the "latest"

- doc/src/osc.md
- openstack_cli/src/network/v2/router/conntrack_helper.rs
- openstack_cli/src/network/v2/router/l3_agent.rs
Add 2 network router subresources in the CLI.
Note that it only enables CLI coverage and not verifies that openapi
schema of the operation was correct, so the call may still fail.
> feat: add network.router.{conntrack_helper,l3_agent}

- openstack_cli/src/network/v2/_tag.rs_
tell clippy to ignore tag module being included multiple times since
this is exactly what we want.
> chore: add clippy exception on common tag module

- doc/src/osc.md
- openstack_cli/src/cli.rs
use claps `next_help_heading` and `display_order` to visually separate
global options from operation options.
> feat: visually separate global options in help message

- openstack_sdk/src/auth.rs
new chrono release deprecated above call. Replace it with
`chrono::Duration::try_days()` call.
> chore: replace deprecated chrono::Duration::days call

- Cargo.lock
- Cargo.toml
- openstack_sdk/Cargo.toml
reqwest adopted updated http and hyper libs so now we can update those
dependencies together.
> chore: update http/reqwest/hyper lib

- Cargo.lock
- Cargo.toml
- openstack_sdk/Cargo.toml
serde_yaml is deprecated, but also unused since cli doesn't support
direct yaml output anymore. SDK is relying on `config`. We can safely
drop serde_yaml dep.
> chore: drop serde_yaml dependency

- openstack_cli/src/lib.rs
"variant name ends with the enum's name" linter warning make sense, but
we generate the code this way for now so allow it.
> fix: whitelist linter warning

- .github/workflows/committed.yml
- .github/workflows/linters.yml
committed must be working only on pull requests, but we want to keep
some other changes from the previous change. So undo only partial
changes.
> fix(ci): Undo merging of commited into linters workflow

- README.md
Add small benchmark comparing performance of osc with the one of
python-openstackclient into the project readme.
> feat(doc): Add small benchmark into readme

- .github/workflows/functional.yml
Add files filter to functional test workflow to only run when
Cargo.{lock,toml} or anything und the sdk/cli code has been modified.
This allows to skip functests on doc-only or workflow optimization
changes.
> chore(ci): Run functional tests only when necessary

- .github/workflows/ci.yml
Set NEXTEST_RETRIES env to allow retry of the unittests. This is
currently a workaround for flaky unittest of sdk with the webhook.
> chore(ci): Enable unittest retry

- Cargo.lock
- Cargo.toml
it is impossible to build fuzz target on musl without adding more
packages and cargo-dist is not in favor of that. For now remove musl
target to make a release and in next steps replace cargo-dist with other
way of building artifacts.
> chore(ci): Temporarily disable musl target

- .github/workflows/ci.yml
- .github/workflows/release.yml
Replace cargo-dist with regular GitHub actions to build artifacts.
This is required to solve carg-dist not supporting enough customization.
> chore(ci): Replace cargo-dist

- openstack_sdk/src/lib.rs
- openstack_sdk/src/service_authority.rs
- openstack_sdk/static/service-types.json
- typos.toml
In order to streamline OpenStack endpoint and version discovery it is
necessary to start consuming service authority data.
> feat(sdk): Add service authority data

- openstack_sdk/src/api/client.rs
- openstack_sdk/src/openstack.rs
- openstack_sdk/src/openstack_async.rs
Centralize endpoint contatenation method into the base client trait
dropping it from sync and async clients. Add some tests to verify
combination logic.
> feat(sdk): Deduplicate endpoint construction method

- openstack_sdk/src/catalog.rs
- openstack_sdk/src/service_authority.rs
- openstack_sdk/src/types.rs
Start relying on the service authority data in the catalog. This also
allows to get rid of hardcoded service type aliases.
> feat(sdk): Start consuming service_authority

- openstack_sdk/src/catalog.rs
- openstack_sdk/src/openstack.rs
- openstack_sdk/src/openstack_async.rs
According to the formal service catalog consumption process it should be
possible to skip service discovery. Add default to skip discovery for
object-store service and process configuration options
(XXX_skip_discovery: bool).
> feat(sdk): Add possibility to skip version discovery

- Cargo.lock
- openstack_cli/src/bin/osc.rs
- openstack_cli/src/error.rs
- openstack_sdk/Cargo.toml
- openstack_sdk/src/api/error.rs
- openstack_sdk/src/api/find.rs
- openstack_sdk/src/api/ignore.rs
- openstack_sdk/src/api/paged.rs
- openstack_sdk/src/api/paged/iter.rs
- openstack_sdk/src/api/paged/pagination.rs
- openstack_sdk/src/api/rest_endpoint.rs
- openstack_sdk/src/catalog.rs
- openstack_sdk/src/catalog/discovery.rs
- openstack_sdk/src/catalog/error.rs
- openstack_sdk/src/catalog/service_endpoint.rs
- openstack_sdk/src/config.rs
- openstack_sdk/src/error.rs
- openstack_sdk/src/openstack.rs
- openstack_sdk/src/openstack_async.rs
- openstack_sdk/src/state.rs
- openstack_sdk/src/types/api_version.rs
anyhow is great at adding context to the errors, but it is recommended
to use anyhow in client facing tools, while thiserror in libs. Using it
makes it quite ugly to get good errors in the cli. So get rid of it and
instead extend base errors to be self containing all required
information.
> refactor(sdk): Get rid of anyhow in openstack_sdk

- doc/src/osc.md
- openstack_cli/src/api/mod.rs
Keystone is using actively PATCH http method instead of post. Add it to
the `api` command.
> feat(cli): Add support for patch method in `api` call

- deny.toml
url lib pulls new dependencies which are of unicode-3 license. Since it
is OSI approved allow it.
> chore(compliance): Allow "unicode-3.0" license

- .github/workflows/ci.yml
- .github/workflows/release.yml
Now that carg-dist is back and builds are prepared in every PR it makes
no sense to do explicit testing on all platforms (there are no platform
specific features in the code anyway). Disable some platforms from the
matrix.
> chore(ci): Disable CI tests jobs on other platforms

- .github/workflows/release.yml
- Cargo.toml
Last step of cargo-dist was not updated properly and it is not able to create GH release as required in order to upload artifacts.
> fix(ci): Fix broken cargo-dist releasing

- README.md
Include information about `cargo-audit` and `GitHub Attestations` on the
main readme.
> feat(doc): Document cargo-audit and GH Attestations

- .pre-commit-config.yaml
- committed.toml
- ignore renovate commites (since type may not be set)
- add committed check to pre-commit
> chore(ci): Improve `committed` configuration

- .github/workflows/release-plz.yml
Latest ruust-toolchain action requires toolchain to be set. Sadly this
was only detected in the failed release-plz run.
> fix(ci): Choose toolchain in the release-plz workflow

- structable_derive/src/structable.rs
When we output empty data ("") `cli_table` is breaking the output layout.
There are some places in the code of `cli_table` that explicitly use " "
for empty cells, so use it directly on our side.
> fix: Fix table output for empty data

- openstack_sdk/src/config.rs
- openstack_sdk/src/error.rs
- openstack_sdk/src/openstack.rs
- openstack_sdk/src/openstack_async.rs
- openstack_sdk/src/utils.rs
Add support for `cacert` clouds.yaml option in a same way as python
tooling. This gives possibility to trust self-signed server
certificates.
> feat(ssl): Add possibility to add custom root SSL ca

- doc/src/osc.md
- openstack_cli/src/api/mod.rs
in the `osc api` call first positional parameter is the service type and
not the service name. Improve the helpstring and rename the parameter to
underline this.
> docs(cli): Clarify the `service` parameter of the API command

- Cargo.toml
- openstack_sdk/src/auth/authtoken.rs
- openstack_sdk/src/catalog.rs
- openstack_sdk/src/catalog/discovery.rs
- openstack_sdk/src/catalog/error.rs
It can happen that discovery document is screwed. In certain cases there
are ways how to deal with those issues (i.e. InvalidPort). In any way
use the catalog endpoint when unrecoverable errors occur.
> fix(auth): Deal with InvalidPort in discovery doc

- openstack_sdk/src/api/ignore.rs
- openstack_sdk/src/api/object_store/v1/account/get.rs
- openstack_sdk/src/api/object_store/v1/container/get.rs
- openstack_sdk/src/api/paged.rs
- openstack_sdk/src/api/paged/next_page.rs
- openstack_sdk/src/api/paged/pagination.rs
- openstack_sdk/src/test/client.rs
Access to a new cloud uncovered one interesting case. There is a single
server in the cloud in the error state and Nova returns 404 for access
by name, while it finds it in the list. However, since this is the only
entry in the list pagination tries to get a next page with the marker
and get's back 400 (invalid marker). For the keyset pagination we should
really stop trying fetching next page when no information about the next
page is available. Swift is not using keyset pagination, and so set it
in the `RestEndpoint` properly while implementing reasonable pagination
using w3c `Link` header (thanks to GitLab SDK implementation).
> fix(pagination): Address new cornercase in pagination

- doc/src/osc.md
- openstack_cli/src/cli.rs
- openstack_cli/src/lib.rs
- openstack_sdk/src/config.rs
- openstack_sdk/src/lib.rs
- openstack_sdk/src/openstack_async.rs
- openstack_sdk/src/state.rs
Add `--os-project-id`/`--os-project-name` cli parameters to authorize
against a different project (not the one in the clouds.yaml).
> feat: Allow overriding project in cli

- openstack_sdk/src/state.rs
User is not expected to do anything when the auth cache file is absent
or cannot be opened. Because of that it makes no sense to log this as
warning.
> chore: Absent state file is not a warning

- openstack_cli/src/network/v2/port/create.rs
- openstack_cli/src/network/v2/port/list.rs
- openstack_cli/src/network/v2/port/set.rs
- openstack_cli/src/network/v2/port/show.rs
dns_assignments in Neutron are not having any schema information. This
leads to ser/deser issues when the fiels is populated (is usually not
the case in devstack, but often with real clouds). Add required
information to the schema so that cli knows it is a complex object
treating it as json value.
> fix(cli): Fix network.port.dns_assignments schema

- .github/workflows/linters.yml
Move from the master branch of typos to the released version to reduce
amount of updates and improve stability.
> chore(ci): Switch to released version of typos

- Cargo.lock
- Cargo.toml
- openstack_sdk/Cargo.toml
- openstack_sdk/src/api/paged/iter.rs
Using an iter approach to consume paginated data was not tested
properly. This results in a swift requests ending in an endless loop.
Add basic tests and add support for `marker` based pagination that works
for swift.
> fix(pagination): Fix pagination when using iter

- openstack_cli/src/network/v2/floatingip/create.rs
- openstack_cli/src/network/v2/floatingip/list.rs
- openstack_cli/src/network/v2/floatingip/set.rs
- openstack_cli/src/network/v2/floatingip/show.rs
In some clouds Neutron is deployed with extensions and port_details with
port_forwardings in reality are not strings, but complex objects.
Address this.
> fix: Fix network.fip cli command

- Cargo.lock
- openstack_cli/Cargo.toml
- openstack_cli/src/auth/login.rs
- openstack_cli/src/bin/osc.rs
- openstack_cli/src/error.rs
- openstack_cli/src/lib.rs
- openstack_cli/src/output.rs
- openstack_sdk/src/api/error.rs
Start switch from anyhow to eyre/color-eyre for error handling in the
cli due to a much more user friendly reporting.
> feat(cli): Start switch to eyre for error handling

- openstack_cli/src/common.rs
Previously condition for the input data was wrongly evaluating to read
the data from stdin when it is not a terminal or file name was unset. It
makes no sense and stdin should be used when both conditions are true.
'else' branch is looking at the passed file name and still select stdin
when fname is '-'.
> fix: change condition in non-terminal data upload

- openstack_cli/src/network/v2/subnetpool/create.rs
- openstack_cli/src/network/v2/subnetpool/list.rs
- openstack_cli/src/network/v2/subnetpool/set.rs
- openstack_cli/src/network/v2/subnetpool/show.rs
Hardwire subnetpool.ip_version to be integer
Neutron treats ip_version as integer but the apidef does not tell anything about that. Implement hard overwrite.
Change-Id: I71a3416bb09325bbe8d8058d2d412023ea3a8c5f
Changes are triggered by https://review.opendev.org/926183
> fix: Repair subnetpool.ip_version field

- openstack_sdk/src/types.rs
- openstack_sdk/src/types/identity/v3.rs
Mentioned derives are required for the POC of the OpenStackTUI.
> chore: Add Eq/PartialEq derives in some types

- .github/workflows/release.yml
- Cargo.toml
Regenerate and re-fix workflow for the cargo-dist.  We also want to be
sure binaries are uploaded into the openstack_cli release and not only
in the vX.Y.Z what requires changes in the template again. For now
restore the carg-dist's native workflow and decide later how to ensure
the hardening.
> chore: Update cargo-dist workflow

- openstack_cli/src/compute/v2/floating_ip/create.rs
- openstack_cli/src/compute/v2/floating_ips_bulk/create.rs
- openstack_cli/src/compute/v2/floating_ips_bulk/set.rs
- openstack_sdk/src/api/compute/v2/floating_ip/create.rs
- openstack_sdk/src/api/compute/v2/floating_ips_bulk/create.rs
- openstack_sdk/src/api/compute/v2/floating_ips_bulk/set.rs
Flip use of UNSET
in the previous change we added support for UNSET to have empty schema. It is more logical to use UNSET when the schema is not defined and not when it is empty. Fix that.
Change-Id: I6568ca826d119b42f74d3f2ee9a691ac1278bc26
Changes are triggered by https://review.opendev.org/926496
> chore: Update compute.floatingip

- openstack_sdk/src/api/rest_endpoint.rs
- openstack_sdk/src/catalog.rs
- openstack_sdk/src/catalog/discovery.rs
- openstack_sdk/src/types.rs
Extend microversion handling logic to also support placement service.
- add service type
- set mv for the service requests
- use max_version before the min_version as service version when version
itself is not set
- get main service type before listing aliases of the service type (to
work properly when requested service type is itself an alias).
> feat: Add support for placement microversion

- openstack_cli/src/block_storage/v3/attachment/list.rs
- openstack_cli/src/block_storage/v3/snapshot/list.rs
- openstack_cli/src/block_storage/v3/volume/list.rs
- openstack_sdk/src/api/block_storage/v3/attachment/list.rs
- openstack_sdk/src/api/block_storage/v3/attachment/list_detailed.rs
- openstack_sdk/src/api/block_storage/v3/snapshot/list.rs
- openstack_sdk/src/api/block_storage/v3/snapshot/list_detailed.rs
- openstack_sdk/src/api/block_storage/v3/volume/list.rs
- openstack_sdk/src/api/block_storage/v3/volume/list_detailed.rs
Fix QP name for listing volumes
There is a typo in a parameter name `all_tenans` where `all_tenants` should be.
Also set that limit can not be negative.
Change-Id: I11c53ad33911a9b95c419f94c5e406a3b6347226
Changes are triggered by https://review.opendev.org/926823
> fix: Corrected volume query parameter name

- .github/workflows/release-plz.yml
Wrong action parameter has being used in the release-plz action (package
instead of manifest_path)
> chore(ci): Fix release-plz action

- .github/workflows/release-plz.yml
- openstack_tui/Cargo.toml
Apparently release-plz does not really support one PR per package of a
workspace.
> chore(ci): Undo release-plz per package

- .github/workflows/ci.yml
- .github/workflows/linters.yml
- Cargo.toml
- Dockerfile
- openstack_tui/Cargo.toml
- Code is using more features than declared in the Cargo.toml
- CI jobs are not triggered on openstack_tui project changes
- openstack_tui is not included in default workspace members resulting
in being skipped in the tests
- fix docker build
> fix: Correct CI for openstack_tui

- openstack_sdk/src/api.rs
- openstack_sdk/src/api/find.rs
It may be desired to find resource by name explicitly rather then guess
whether identifier is id or name in order to save API roundtrip known
not to return data. This is going to be used in the cli to allow
different handling of the path parameters allowing user to explicitly
specify whether the input is name or id.
> feat(sdk): Add find_by_name method

- doc/src/osc.md
- openstack_cli/src/identity/v3/domain/user/role/delete.rs
- openstack_cli/src/identity/v3/domain/user/role/list.rs
- openstack_cli/src/identity/v3/domain/user/role/set.rs
- openstack_cli/src/identity/v3/domain/user/role/show.rs
- openstack_cli/src/identity/v3/group/user/delete.rs
- openstack_cli/src/identity/v3/group/user/set.rs
- openstack_cli/src/identity/v3/group/user/show.rs
- openstack_cli/src/identity/v3/os_inherit/domain/user/role/inherited_to_project/delete.rs
- openstack_cli/src/identity/v3/os_inherit/domain/user/role/inherited_to_project/get.rs
- openstack_cli/src/identity/v3/os_inherit/domain/user/role/inherited_to_project/inherited_to_projects.rs
- openstack_cli/src/identity/v3/os_inherit/project/user/role/inherited_to_project/delete.rs
- openstack_cli/src/identity/v3/os_inherit/project/user/role/inherited_to_project/get.rs
- openstack_cli/src/identity/v3/os_inherit/project/user/role/inherited_to_project/inherited_to_projects.rs
- openstack_cli/src/identity/v3/project/user/role/delete.rs
- openstack_cli/src/identity/v3/project/user/role/list.rs
- openstack_cli/src/identity/v3/project/user/role/set.rs
- openstack_cli/src/identity/v3/project/user/role/show.rs
- openstack_cli/src/identity/v3/system/user/role/delete.rs
- openstack_cli/src/identity/v3/system/user/role/list.rs
- openstack_cli/src/identity/v3/system/user/role/set.rs
- openstack_cli/src/identity/v3/system/user/role/show.rs
- openstack_cli/src/network/v2/port/create.rs
- openstack_cli/src/network/v2/port/list.rs
- openstack_cli/src/network/v2/port/set.rs
- openstack_cli/src/network/v2/port/show.rs
- openstack_sdk/src/api/network/v2/port/create.rs
When path_parameter contain something like `user_id` it is more
efficient (and provides a UX with more control) to accept
`user-id|user-name` from the user. This is achieved by introducing
resource links in the path parameters. When link is present parameter is
being processed differently.
Modify Keystone schema generation to insert link to the user everywhere
where `user_id` path parameter is present.
Change-Id: I8bf3d14dc751bdb97111a63dddfd0b604cf06abc
Changes are triggered by https://review.opendev.org/927746
> feat: Add resource link in path parameters

- openstack_cli/src/identity/v3/os_inherit/domain/group/role/inherited_to_project/delete.rs
- openstack_cli/src/identity/v3/os_inherit/domain/group/role/inherited_to_project/get.rs
- openstack_cli/src/identity/v3/os_inherit/domain/group/role/inherited_to_project/inherited_to_projects.rs
- openstack_cli/src/identity/v3/os_inherit/domain/user/role/inherited_to_project/delete.rs
- openstack_cli/src/identity/v3/os_inherit/domain/user/role/inherited_to_project/get.rs
- openstack_cli/src/identity/v3/os_inherit/domain/user/role/inherited_to_project/inherited_to_projects.rs
Same way as for user we add resource link to the domain_id path
parameter allowing cli user to use `--domain-id|--domain-name`.
Change-Id: Ibf220ff2b3cd11d639b6b1c5fdff66da6fa80972
Changes are triggered by https://review.opendev.org/927860
> feat: Add resource link to domain_id path parameter

- README.md
Since there are no global releases anymore the normal installer link is not working. Switch (at least temporarily) to the full link of the 0.7.0 release while looking for the better solution
> chore: Update install binary link

- openstack_tui/src/components/compute/flavors.rs
- openstack_tui/src/components/compute/servers.rs
- openstack_tui/src/components/image/images.rs
- openstack_tui/src/components/network/networks.rs
- openstack_tui/src/components/network/subnets.rs
- openstack_tui/src/components/table_view.rs
Some resources have lot of content in the describe view and native
desire is to scoll it as well.
- Add <TAB> key to jump between table and the describe
- Use gray color for describe when not "active"
- Add vertical scrolling in the describe
> feat(tui): Add scrolling in the resource describe

- Cargo.lock
- openstack_cli/Cargo.toml
- openstack_cli/src/error.rs
- openstack_cli/src/lib.rs
- openstack_sdk/src/config.rs
When user has not specified `--os-cloud` param but the cli is running in
an interactive mode we can invoke dialoguer to offer user configured
clouds to select (similarly how it is done in the tui).
> feat(cli): Interactive cloud connection

- openstack_tui/.config/config.json5
- openstack_tui/src/action.rs
- openstack_tui/src/app.rs
- openstack_tui/src/cloud_services.rs
- openstack_tui/src/cloud_services/identity.rs
- openstack_tui/src/cloud_worker.rs
- openstack_tui/src/components.rs
- openstack_tui/src/components/compute/flavors.rs
- openstack_tui/src/components/compute/servers.rs
- openstack_tui/src/components/describe.rs
- openstack_tui/src/components/error_popup.rs
- openstack_tui/src/components/header.rs
- openstack_tui/src/components/image/images.rs
- openstack_tui/src/components/network/networks.rs
- openstack_tui/src/components/network/subnets.rs
- openstack_tui/src/components/project_select_popup.rs
- openstack_tui/src/components/table_view.rs
- openstack_tui/src/config.rs
In authenticated session it is possible to list available projects
(/auth/projects). Implement another selector popup to change the session
scope.
- add new popup
- make popup components long living components to better handle overall
session data
Open:
- auth with ApplicationCredentials does not allow changing scope
- admin does not have list of available scopes at all
> feat: Add project selection

- openstack_tui/src/components/compute/flavors.rs
- openstack_tui/src/components/compute/servers.rs
- openstack_tui/src/components/network/networks.rs
- openstack_tui/src/components/network/subnets.rs
- openstack_tui/src/components/table_view.rs
Avoid crash when we try to call some actions on row which is not
selected (i.e. when no rows exist)
> fix: Process row only when selected

- Cargo.toml
Listing fuzz in workspace exclude is not necessary
> chore: Remove fuzz from exclude

- openstack_cli/src/network/v2/agent/create.rs
- openstack_cli/src/network/v2/agent/list.rs
- openstack_cli/src/network/v2/agent/set.rs
- openstack_cli/src/network/v2/agent/show.rs
- agent.alive is boolean
- agent.configurations is an object
None of them is having any type marker in neutron-lib -> hardcode.
Change-Id: Ib1d394baf9f6375d541b38b21b9b7a30898a1fb3
Changes are triggered by https://review.opendev.org/930561
> fix: Fix network.agent property types

- Cargo.lock
- Cargo.toml
- openstack_cli/Cargo.toml
- openstack_cli/src/bin/osc.rs
- openstack_tui/Cargo.toml
- openstack_tui/src/utils.rs
Practice showed that neither better-panic gives any benefit, nor
human-panic (it is not possible to upload generated toml file to GitHub
easily). Get rid of them restoring eyre reporting functionality with
some styling.
> chore: Drop better/human-panic

- openstack_cli/src/identity/v3/user/access_rule.rs
- openstack_cli/src/identity/v3/user/application_credential.rs
- xtask/src/bin/osc-cli-md.rs
- render complete command under the subcommands instead of only the
subcommand name
- address few issues in the identity docstrings
> chore: Show full osc command in the doc

- Cargo.lock
- openstack_cli/src/bin/osc.rs
- openstack_cli/src/cli.rs
- openstack_cli/src/lib.rs
- openstack_sdk/Cargo.toml
- openstack_sdk/src/config.rs
Similarly to openstacksdk/cli support `--os-client-config-file` and
`--os-client-secure-file` to specify alternative path to the
configuration files.
> feat: Add support for --os-client-config-file

- openstack_cli/Cargo.toml
- openstack_cli/src/dns/mod.rs
- openstack_cli/src/lib.rs
- openstack_sdk/Cargo.toml
- openstack_sdk/src/api.rs
- openstack_sdk/src/api/dns.rs
- openstack_sdk/src/types.rs
codegenerator is ready to start pushing first DNS changes.
> feat: Initialize the DNS service support

- openstack_cli/README.md
- openstack_cli/src/lib.rs
- openstack_sdk/src/auth/authtoken_scope.rs
- openstack_sdk/src/config.rs
After a bit back and forth on how to actually implement the proposed solution https://github.com/gtema/openstack/issues/608#issuecomment-2384546393, this is what should work and not break anything (since the last release), though the order of configurations has been changed to match what the python OpenStackSDK does.
I have removed the previous solution with `TryFrom`, but I can add it back if desired.
> feat: add the ability to specify the configs to load via a builder

- Cargo.lock
- openstack_cli/Cargo.toml
- openstack_cli/src/output.rs
comfy-table provides more styling options including dynamic content
wrapping and UTF8 borders (it would be possible for the user to
customize output as desired). Project introduces few additional
dependencies (which are mostly anyway three) but is having more stars on
GitHub and activity.
> feat: Switch from cli-table to comfy-table

- openstack_cli/src/dns/v2/zone/share/list.rs
- openstack_sdk/src/api/dns/v2/zone/recordset/create.rs
zone_name is a readOnly param and is not a uuid
Change-Id: If9a21d32ce431754a683c10e3e059def4bb3d9ba
Changes are triggered by https://review.opendev.org/931656
> fix: Fix dns recordset schema

- openstack_tui/src/components/table_view.rs
Fix condition determining end of the list to prevent showing
non-existing entry.
> fix: Fix "down" button on last entry

- openstack_tui/src/app.rs
- openstack_tui/src/components/fuzzy_select_list.rs
When resource select popup is being closed reset the user input
> fix: Reset input when resource select popup closed

- release-plz.toml
It is desired to distribute binaries better enabling `cargo install` and
reasonably stable download url. This should be achievable (even not
perfect) when binary packages are all having same version so that in git
we have only one tag where artifacts will be stored.
> chore: Add osc and tui into single version group

- openstack_tui/src/cloud_worker.rs
- openstack_tui/src/cloud_worker/compute.rs
- openstack_tui/src/cloud_worker/compute/types.rs
- openstack_tui/src/cloud_worker/identity.rs
- openstack_tui/src/cloud_worker/identity/types.rs
- openstack_tui/src/cloud_worker/image.rs
- openstack_tui/src/cloud_worker/image/types.rs
- openstack_tui/src/cloud_worker/network.rs
- openstack_tui/src/cloud_worker/network/types.rs
- openstack_tui/src/cloud_worker/types.rs
- openstack_tui/src/components/compute/aggregates.rs
- openstack_tui/src/components/compute/flavors.rs
- openstack_tui/src/components/compute/hypervisors.rs
- openstack_tui/src/components/compute/servers.rs
- openstack_tui/src/components/header.rs
- openstack_tui/src/components/identity/projects.rs
- openstack_tui/src/components/image/images.rs
- openstack_tui/src/components/network/networks.rs
- openstack_tui/src/components/network/subnets.rs
- openstack_tui/src/utils.rs
Add a way for the service cloud_worker to cover resources it support to
heavily reduce cound of match branches in the main cloud_worker event
loop.
Add a test for trimming header cells addressing few potential panics.
> chore: Beter modularize cloud worker services

- openstack_tui/src/cloud_worker/compute.rs
- openstack_tui/src/cloud_worker/network.rs
- openstack_tui/src/components/home.rs
Home mode uses `expect` to access project_id of the current scope. This
causes unpleasant crash when initially connected with the domain scope.
Change it to be conditional and show "Not available" for quotas when
no data can be fetched.
> fix: Do not crash when connected with domain_scope

- openstack_tui/.config/config.json5
- openstack_tui/src/action.rs
- openstack_tui/src/app.rs
- openstack_tui/src/cloud_worker/identity.rs
- openstack_tui/src/cloud_worker/identity/types.rs
- openstack_tui/src/cloud_worker/types.rs
- openstack_tui/src/components/header.rs
- openstack_tui/src/components/identity.rs
- openstack_tui/src/components/identity/group_users.rs
- openstack_tui/src/mode.rs
- add view for managing group users
- sketch commands that would be available in individual identity modes
> feat: Add group_users mode

- openstack_tui/src/components/describe.rs
Clear "Describe" mode scroll and content every time we get new data.
> fix: Clear the describe on reset

- openstack_tui/.config/config.json5
- openstack_tui/src/app.rs
- openstack_tui/src/components/fuzzy_select_list.rs
- openstack_tui/src/components/project_select_popup.rs
- openstack_tui/src/components/resource_select_popup.rs
- openstack_tui/src/config.rs
- openstack_tui/src/mode.rs
initializing hashmap with Box<dyn> objects is not trivial in Rust (at
least I do not see a nice way to do that now. In any way inserting
individual value with insert seems nicer then creating variable for
every component and then assigning them into the hashmap.
> chore: Change components map initialization

- openstack_tui/.config/config.json5
- openstack_tui/src/components/table_view.rs
When table has no data columns are sized at 1 char.
> fix: Set proper default column width

- openstack_tui/src/cloud_worker/network.rs
- openstack_tui/src/components/network/security_group_rules.rs
Well, almost. Apparently use of BTreeSet for array query parameters in
network is not appropriate since it is absolutely correct to request
`sort_key=f1&sort_key=f2&sort_key=f3&sort_dir=asc&sort_dir=asc&sort_dir=asc`
> chore: Re-enable sorting in network

- openstack_tui/.config/config.json5
- openstack_tui/src/components/header.rs
- openstack_tui/src/config.rs
It makes quite a sence to visualy separate mode keybindings into filters
and actions.
Also replace all 'd' for describe with 'y' as YAML (similarly to k9s) to
reduce change of collisions with specific actions willing to use 'd'
(i.e. delete)
> feat: Separate keybindings into actions and filters

- Cargo.lock
Address https://rustsec.org/advisories/RUSTSEC-2024-0399 in rustls
> chore: Update locked dependendcy

- .github/workflows/linters.yml
sarif tools building takes time and requires higher msrv than our
project, so install them as binaries using cargo-binstall
> chore: Install sarif tools using binstall

- openstack_sdk/src/auth/authtoken_scope.rs
- openstack_sdk/src/types/identity/v3.rs
When project_id is set in the auth but no project_domain is present
Keystone refuses to auth since it checks project_name before the
project_id (which is normally sufficient and does not require
domain_infos). When project_id is present in the auth config do not set
project_name.
> fix: Auth with project_id and no domain info set

- openstack_cli/src/load_balancer/v2/healthmonitor/list.rs
- openstack_cli/src/load_balancer/v2/l7policy/list.rs
- openstack_cli/src/load_balancer/v2/l7policy/rule/list.rs
- openstack_cli/src/load_balancer/v2/listener/list.rs
- openstack_cli/src/load_balancer/v2/loadbalancer/list.rs
- openstack_cli/src/load_balancer/v2/pool/list.rs
- openstack_cli/src/load_balancer/v2/pool/member/list.rs
- openstack_cli/src/network/v2/availability_zone/list.rs
Some resources uses `state` or `operating_status` as a sort of `status`
property. Set `status` StructTable marcros for such fields so that
output coloring use those fields.
Change-Id: I1c1faa0f69e1d22b6230db2df90a981ca496e643
Changes are triggered by https://review.opendev.org/936928
> feat: Add `status` structable macros for alternative field

- openstack_sdk/src/auth/authtoken_scope.rs
- openstack_sdk/src/config.rs
- openstack_sdk/src/state.rs
- openstack_sdk/src/types/identity/v3.rs
`system_scope: all` entry in the clouds.yaml will be treated as system
scope same as python-openstackclient does
> feat: Add support for system scope

- openstack_sdk/README.md
- openstack_sdk/src/api.rs
- openstack_sdk/src/api/find.rs
- openstack_sdk/src/api/ignore.rs
- openstack_sdk/src/api/paged.rs
- openstack_sdk/src/api/paged/iter.rs
- openstack_sdk/src/api/paged/next_page.rs
- openstack_sdk/src/api/rest_endpoint.rs
- openstack_sdk/src/auth/authtoken.rs
- openstack_sdk/src/auth/v3applicationcredential.rs
- openstack_sdk/src/auth/v3password.rs
- openstack_sdk/src/auth/v3token.rs
- openstack_sdk/src/auth/v3totp.rs
- openstack_sdk/src/auth/v3websso.rs
- openstack_sdk/src/catalog.rs
- openstack_sdk/src/catalog/discovery.rs
- openstack_sdk/src/catalog/error.rs
- openstack_sdk/src/catalog/service_authority.rs
- openstack_sdk/src/catalog/service_endpoint.rs
- openstack_sdk/src/openstack.rs
- openstack_sdk/src/openstack_async.rs
- openstack_sdk/src/test/client.rs
- openstack_sdk/src/types.rs
- openstack_sdk/src/types/api_version.rs
- structable_derive/tests/main.rs
There is a wide spread recommendation to avoid using to_string() in
favor of into() and to_owned(). Follow it except few places where it
must (at least for now) stay.
> chore: Get rid of `to_string` where possible

- README.md
Bring back links for installation pointing to the latest release.
> chore: Update links to latest release

- openstack_sdk/src/openstack.rs
- openstack_sdk/src/openstack_async.rs
Test on another cloud with multiple regions showed that region_name config
setting was not properly respected during catalog processing.
> fix: Respect region_name set in the config

- openstack_sdk/src/auth.rs
- openstack_sdk/src/auth/authtoken.rs
- openstack_sdk/src/openstack.rs
- openstack_sdk/src/openstack_async.rs
- openstack_sdk/src/state.rs
- openstack_sdk/src/types/identity/v3.rs
Allow client to figure out auth status: expired, valid, soon_to_expire
to allow easy reaction.
> feat: Add get_auth_state method to obtain auth status

- openstack_tui/src/cloud_worker/block_storage/v3/backup/delete.rs
- openstack_tui/src/cloud_worker/block_storage/v3/snapshot/delete.rs
- openstack_tui/src/cloud_worker/block_storage/v3/volume/delete.rs
- openstack_tui/src/cloud_worker/compute/v2/aggregate/delete.rs
- openstack_tui/src/cloud_worker/compute/v2/server/delete.rs
- openstack_tui/src/cloud_worker/dns/v2/zone/delete.rs
- openstack_tui/src/cloud_worker/dns/v2/zone/recordset/delete.rs
- openstack_tui/src/cloud_worker/identity/v3/group/delete.rs
- openstack_tui/src/cloud_worker/identity/v3/group/user/delete.rs
- openstack_tui/src/cloud_worker/identity/v3/project/delete.rs
- openstack_tui/src/cloud_worker/identity/v3/user/application_credential/delete.rs
- openstack_tui/src/cloud_worker/identity/v3/user/delete.rs
- openstack_tui/src/cloud_worker/image/v2/image/delete.rs
- openstack_tui/src/cloud_worker/load_balancer/v2/healthmonitor/delete.rs
- openstack_tui/src/cloud_worker/load_balancer/v2/listener/delete.rs
- openstack_tui/src/cloud_worker/load_balancer/v2/loadbalancer/delete.rs
- openstack_tui/src/cloud_worker/load_balancer/v2/pool/delete.rs
- openstack_tui/src/cloud_worker/load_balancer/v2/pool/member/delete.rs
- openstack_tui/src/cloud_worker/load_balancer/v2/quota/delete.rs
- openstack_tui/src/cloud_worker/network/v2/network/delete.rs
- openstack_tui/src/cloud_worker/network/v2/router/delete.rs
- openstack_tui/src/cloud_worker/network/v2/security_group/delete.rs
- openstack_tui/src/cloud_worker/network/v2/security_group_rule/delete.rs
- openstack_tui/src/cloud_worker/network/v2/subnet/delete.rs
When TUI user invoked delete event we want to know it was completed
successfully. For that send a response with request data and explicit Null as
response.
Change-Id: I844d2d89883481b4a874aadf4aee8156c84cf536
Changes are triggered by https://review.opendev.org/940676
> feat: Send response action also for delete events

- Cargo.lock
- openstack_tui/Cargo.toml
- openstack_tui/src/cloud_worker.rs
- openstack_tui/src/error.rs
Implement automatic reconnection when token expired or is close to
expire (10 sec). This is only done before the OpenStack API request
processing.
> feat: Reconnect when token expired

- openstack_cli/tests/image/v2/image/file/roundtrip.rs
For some reason it was working before, but is not working now.
> fix: Use '--file' instead of '-f' in the image functest

- openstack_tui/src/cloud_worker.rs
Perform block-storage endpoint version discovery in the TUI. This fixes
used microversion and at the same time sets proper region.
> fix: Discover block-storage endpoint in the TUI

- openstack_cli/src/bin/osc.rs
- openstack_cli/src/common.rs
- openstack_cli/src/error.rs
Another unwrap is being replaced with human readable error saying that
source name must be specified when uploading image without piping the
stdin.
> feat: Return readable error instead of crashing in data upload

- openstack_cli/Cargo.toml
- openstack_cli/src/container_infrastructure_management/mod.rs
- openstack_cli/src/container_infrastructure_management/v1.rs
- openstack_sdk/Cargo.toml
- openstack_sdk/src/api.rs
- openstack_sdk/src/api/container_infrastructure_management.rs
- openstack_sdk/src/api/container_infrastructure_management/v1.rs
- openstack_sdk/src/api/rest_endpoint.rs
- openstack_sdk/src/types.rs
Prepare for the magnum code being generated. This adds basic folder structure,
service type and forces version discovery to also support magnum requests.
> feat: Initialize magnum service structure

- openstack_cli/src/network/v2/router/add_external_gateways.rs
- openstack_cli/src/network/v2/router/create.rs
- openstack_cli/src/network/v2/router/list.rs
- openstack_cli/src/network/v2/router/remove_external_gateways.rs
- openstack_cli/src/network/v2/router/set.rs
- openstack_cli/src/network/v2/router/show.rs
- openstack_cli/src/network/v2/router/update_external_gateways.rs
- openstack_sdk/src/api/network/v2/router/create.rs
- openstack_sdk/src/api/network/v2/router/set.rs
Recently validation of the external_gateway_info has been modified in
the Neutron so that we are not able to detect the schema anymore. Adapt
it to how it "look like it is intended".
Change-Id: I8976a019cd11b4cb3d8780553bb72b7ce6627519
Changes are triggered by https://review.opendev.org/943036
> feat: Fix network external_gateway_info schema

- structable_derive/src/structable.rs
- structable_derive/tests/main.rs
Current logic outputs requested wide field only in the wide mode. This hurts in
UX and views configuration requiring wide mode by default. Change the logic to
return the wide field in wide more or when it is explicitly requested.
> feat: Allow showing wide field even without wide mode

- openstack_sdk/src/auth.rs
- openstack_sdk/src/openstack.rs
- openstack_sdk/src/openstack_async.rs
When the Auth response does not contain the token where we expect it a cryptic
error is thrown (well, this only handles with incorrect Keystone, but still).
> fix: Handle missing token in the auth response

- Cargo.lock
- openstack_sdk/Cargo.toml
- openstack_sdk/src/api/common.rs
- openstack_sdk/src/api/identity/v3/auth/token/create.rs
- openstack_sdk/src/auth/v3applicationcredential.rs
- openstack_sdk/src/auth/v3password.rs
- openstack_sdk/src/auth/v3token.rs
- openstack_sdk/src/auth/v3totp.rs
- openstack_sdk/src/config.rs
- openstack_sdk/src/openstack_async.rs
- openstack_sdk/src/types.rs
In the config and in auth call we deal with the sensitive data (password,
token, etc). Ensuring it is not leaked it not so trivial but aparently the
`secrecy` crate is able to serve the needs. Since we need to be able to
serialize password into the Json we can't ensure at the moment that the value
does not appear in logs, but at least it will not when the holding structure
is included in the log.
With this we can remove `(crate)` visibility restriction from config structs.
And while on that also finally implement censoring of the json requests to
prevent sensitive auth data to appear in trace logs
> feat: Address sensitive data logging

- openstack_sdk/src/types.rs
- openstack_sdk/src/types/common.rs
Before we drop NumString, IntString, BoolString from the cli copy them into
the SDK so that those can be also reused in the tui.
> feat: Introduce common resonse type helpers

- openstack_sdk/src/api/find.rs
- openstack_sdk/src/api/ignore.rs
- openstack_sdk/src/api/paged.rs
- openstack_sdk/src/api/paged/iter.rs
- openstack_sdk/src/api/paged/next_page.rs
- openstack_sdk/src/api/rest_endpoint.rs
- openstack_sdk/src/test/client.rs
In order to allow downstream users to test their resources create fake client
that can be used together with mock server. This is a first step. In the next
step all existing tests will be converted to this new fake client. Afterwards
it will be exposed dropping current MockServerClient and MockAsyncServerClient.
> feat(test): Introduce FakeOpenStackClient

- Cargo.lock
- openstack_types/Cargo.toml
- structable_derive/src/structable.rs
- structable_derive/tests/main.rs
Add possibility to serialize data in the StrucTable derive macro to
prevent need for NewType wrappers just for the sake of serializing data
into the table.
> feat: Make StructTable serialize the property

- .github/workflows/ci.yml
- openstack_types/src/common.rs
Add possibility to avoid IntString, NumString, BoolString newtypes by
implementing different style of deserializer to be used as
`#[serde(deserialize_with="deser_num_str")]
> fix: Add new deser_num_str and deser_bool_str

- .github/workflows/linters.yml
- .pre-commit-config.yaml
- openstack_types/src/common.rs
filemask on the linters flow was skipping the run on changes into the
openstack_types. Fix that and ensure cargo fmt runs on the latest rust,
cause this is exactly the version the main development happens and now
there is a difference in imports ordering between 1.85 and 1.86
> chore: Fix linter for openstack_types again

- openstack_types/src/block_storage/v3/attachment/response/create.rs
- openstack_types/src/block_storage/v3/attachment/response/get.rs
- openstack_types/src/block_storage/v3/attachment/response/list_detailed.rs
- openstack_types/src/block_storage/v3/attachment/response/set.rs
- openstack_types/src/block_storage/v3/manageable_volume/response/create.rs
- openstack_types/src/block_storage/v3/volume/response/create.rs
- openstack_types/src/block_storage/v3/volume/response/get.rs
- openstack_types/src/block_storage/v3/volume/response/list_detailed.rs
- openstack_types/src/block_storage/v3/volume/response/set.rs
Not all of the fields declared as mandatory are being returned by real
clouds.
Change-Id: I59ed1b1014a6eb91f067b61e3b57a3bb8f4e2b8e
Changes are triggered by https://review.opendev.org/947562
> feat: Fix BS response schemas

- openstack_cli/src/error.rs
- openstack_cli/src/output.rs
- openstack_tui/src/app.rs
- openstack_tui/src/components/table_view.rs
- openstack_tui/src/error.rs
In order to make better error processing we should ensure json
deserialization error is an explitic error with error information and
the source data. We are going to catch it and perhaps have some helpers
improving error reporting.
> feat: Wrap deserialization error into dedicated error

- openstack_sdk/src/api/compute/v2/server/create_20.rs
- openstack_sdk/src/api/compute/v2/server/create_21.rs
- openstack_sdk/src/api/compute/v2/server/create_219.rs
- openstack_sdk/src/api/compute/v2/server/create_232.rs
- openstack_sdk/src/api/compute/v2/server/create_233.rs
- openstack_sdk/src/api/compute/v2/server/create_237.rs
- openstack_sdk/src/api/compute/v2/server/create_242.rs
- openstack_sdk/src/api/compute/v2/server/create_252.rs
- openstack_sdk/src/api/compute/v2/server/create_257.rs
- openstack_sdk/src/api/compute/v2/server/create_263.rs
- openstack_sdk/src/api/compute/v2/server/create_267.rs
- openstack_sdk/src/api/compute/v2/server/create_274.rs
- openstack_sdk/src/api/compute/v2/server/create_290.rs
- openstack_sdk/src/api/compute/v2/server/create_294.rs
- openstack_sdk/src/api/compute/v2/server/create_backup_20.rs
- openstack_sdk/src/api/compute/v2/server/create_backup_21.rs
- openstack_sdk/src/api/compute/v2/server/create_image_20.rs
- openstack_sdk/src/api/compute/v2/server/create_image_21.rs
- openstack_tui/src/cloud_worker.rs
- openstack_types/src/compute/v2/keypair/response/create.rs
- openstack_types/src/compute/v2/keypair/response/get.rs
- keypair create response does not contain ID
- server create response has a response_key (server). This is not really
true, since creation may return reservation_id, but this is not
typical and we can try to find a solution for that later. For now make
sure cli server creation works.
Change-Id: I3f52f0e6686767dcc8862543c4c3a155f42ead0e
Changes are triggered by https://review.opendev.org/948063
> fix: Fix few nova response schemas

- openstack_sdk/src/config.rs
Sometimes it is useful to know from where `clouds.yaml`/`config.yaml`
are being read. Add trace message when certain path has been
successfully loaded.
> chore: Add trace message of config file being used

- .github/workflows/ci.yml
- openstack_types/data/network/v2.26.yaml
- openstack_types/data/network/v2.yaml
- openstack_types/src/network/v2/floatingip/response/create.rs
- openstack_types/src/network/v2/floatingip/response/get.rs
- openstack_types/src/network/v2/floatingip/response/list.rs
- openstack_types/src/network/v2/floatingip/response/set.rs
- openstack_types/tests/mocked/main.rs
- openstack_types/tests/mocked/network/v2/floatingip/mod.rs
- openstack_types/tests/mocked/network/v2/floatingip/response/list.rs
- openstack_types/tests/mocked/network/v2/floatingip/response/mod.rs
- openstack_types/tests/mocked/network/v2/mod.rs
port_details is an object and not array of objects.
Add deserialization mock test
Change-Id: I4095e664d714222d1d1ef8fdac0422393e7c451b
Changes are triggered by https://review.opendev.org/949042
> fix: Fix fip.port_details schema

- openstack_types/data/compute/v2.100.yaml
- openstack_types/data/compute/v2.yaml
- openstack_types/src/compute/v2/server/response/get.rs
- openstack_types/src/compute/v2/server/response/list_detailed.rs
- openstack_types/src/compute/v2/server/response/set.rs
image in the server response may be an empty string if the server was
provisioned from a volume.
Change-Id: I4ec1d5391d373ec1aaba40b0547b06ebc9629ec2
Changes are triggered by https://review.opendev.org/949181
> fix: Fix server schema

- openstack_cli/src/cli.rs
- openstack_cli/src/output.rs
Add `--table-arrangement` cli option to allow user choose between 3
table arrangement strategies:
- dynamic (default) - content is distributed evenly trying to use as
much space as necessary
- dynamic-full-width - spread the output to the full available width
- disabled - use as much space as necessary to render cells (table row
may continue on the next row).
Also fix accidentially ignored `--pretty` modifier when there is
configuration for the requested resource.
> feat: Add table-arrangement output option

- openstack_cli/src/network/v2/floatingip/create.rs
- openstack_cli/src/network/v2/floatingip/set.rs
- openstack_cli/src/network/v2/local_ip/create.rs
- openstack_cli/src/network/v2/local_ip/port_association/create.rs
- openstack_cli/src/network/v2/ndp_proxy/create.rs
- openstack_cli/src/network/v2/subnet/create.rs
- openstack_cli/src/network/v2/subnet/set.rs
- openstack_sdk/src/api/network/v2/floatingip/create.rs
- openstack_sdk/src/api/network/v2/floatingip/set.rs
- openstack_sdk/src/api/network/v2/local_ip/create.rs
- openstack_sdk/src/api/network/v2/local_ip/port_association/create.rs
- openstack_sdk/src/api/network/v2/ndp_proxy/create.rs
- openstack_sdk/src/api/network/v2/subnet/create.rs
- openstack_sdk/src/api/network/v2/subnet/set.rs
- openstack_types/data/network/v2.26.yaml
- openstack_types/data/network/v2.yaml
Some conversion schemes missed explicit null support.
Change-Id: I01ed16f2690c78492a0d8673ad86f67de92c80ae
Changes are triggered by https://review.opendev.org/949561
> fix: Address explicit nullable types in network

- openstack_cli/src/output.rs
`-o wide` should not be necessary for show commands. It is a regression
of the structable rework.
> fix: Ensure `XXX show` returns all fields

- openstack_cli/src/identity/v3/limit/list.rs
- openstack_cli/src/identity/v3/registered_limit/list.rs
- openstack_cli/src/identity/v3/role_assignment/list.rs
- openstack_cli/src/identity/v3/system/group/role/list.rs
- openstack_cli/src/identity/v3/system/user/role/list.rs
- openstack_cli/src/image/v2/task/list.rs
In the cli generation it was assumed that the first element in the
response schema is the object itself. That is used to check whether the
response is list or not. Now the role_assignment schema return `links`
object first breaking that assumption. Extend the check to first look at
the `response_key` that we identified previously.
Change-Id: Ib2cf6e394486ebd0a475ed3d9bba97feefcd5205
Changes are triggered by https://review.opendev.org/950250
> fix: Fix role_assignments command

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/linters.yml
- doc/book.toml
It was intended to run tests with the MSRV and not the clippy. Since
clippy format changes between releases it is not correct to check if the
code formatted with newer clippy passed old clippy. It is relevant for
tests though.
> chore: Do correct testing

- openstack_types/data/object-store/v1.yaml
In swift we service return few integer attributes which can only be
positive. Ensure this is incorporated in the schema.
Change-Id: I23509ca116f607a2b26fa1c01387dbd4f4df705a
Changes are triggered by https://review.opendev.org/950669
> fix: Ensure swift bytes are positive integers

- openstack_types/src/identity/v3/role_assignment/response/list.rs
`prop: {const: True}` should be converted to bool and not to integer.
Change-Id: Ic3775a36c138d451dbad7615bc0e446528d8b0be
Changes are triggered by https://review.opendev.org/950754
> fix: Fix type conversion of const bool

- Cargo.lock
- doc/src/cli/config.md
- openstack_cli/.config/config.yaml
- openstack_cli/Cargo.toml
- openstack_cli/src/config.rs
- openstack_cli/src/output.rs
Add possibility to specify `json_path` as the column configuration in
the configuration file to output only the data under the path. This is
helpful i.e. when listing servers not to show the whole flavor
information, but only show the flavor name using the `/original_name`
json path expression. It is inly applied in the listing operations and
no `-o wide` specified.
> feat: Implement json pointer extractor for the column

- openstack_cli/src/dns/v2/recordset/list.rs
- openstack_cli/src/dns/v2/zone/list.rs
- openstack_cli/src/dns/v2/zone/recordset/list.rs
- openstack_cli/src/dns/v2/zone/share/list.rs
- openstack_sdk/src/api/dns/v2/recordset/list.rs
- openstack_sdk/src/api/dns/v2/zone/list.rs
- openstack_sdk/src/api/dns/v2/zone/recordset/list.rs
- openstack_sdk/src/api/dns/v2/zone/share/list.rs
- openstack_tui/src/cloud_worker/dns/v2/recordset/list.rs
- openstack_tui/src/cloud_worker/dns/v2/zone/list.rs
- openstack_tui/src/cloud_worker/dns/v2/zone/recordset/list.rs
- openstack_tui/src/components/dns/recordsets.rs
- openstack_types/data/dns/v2.1.yaml
- openstack_types/data/dns/v2.yaml
- openstack_types/data/identity/v3.14.yaml
- openstack_types/data/identity/v3.yaml
- openstack_types/data/network/v2.26.yaml
- openstack_types/data/network/v2.yaml
- openstack_types/data/placement/v1.39.yaml
- openstack_types/data/placement/v1.yaml
- openstack_types/data/shared-file-system/v2.89.yaml
- openstack_types/data/shared-file-system/v2.yaml
Fix typo "market" where "marker" should be.
Change-Id: Ic9f94727b6abb33619bde96a610fedad7cc12398
Changes are triggered by https://review.opendev.org/950996
> fix: fix dns qp marker parameter name

- doc/src/SUMMARY.md
- doc/src/possible_errors.md
- openstack_sdk/src/catalog.rs
- openstack_sdk/src/catalog/discovery.rs
- openstack_sdk/src/catalog/error.rs
- openstack_sdk/src/catalog/service_endpoint.rs
- openstack_sdk/src/openstack.rs
- openstack_sdk/src/openstack_async.rs
There are lot of possible service and service catalog misconfiguration.
Introduce a dedicated document describing possible problems, add
references in the warnings or error messages and add few more checks.
Since it is not possible to verify that the service url from discovery
url is working (thanks Glance) it is only possible to do some more
"it does look suspicious" checks with warnings and suggestions how to
deal with that.
Current keystoneauth/openstacksdk are not strictly following the
official version discovery process and may actually exit discovery
earlier than this project does exposing difference in behavior.
> feat: Improve service discovery (hopefully)

- Cargo.lock
- Cargo.toml
- openstack_cli/src/lib.rs
Now that we have added fallible implementation into clap_complete we can
start using it to ensure that when generation of the completion fails we
do not crash.
> fix: Fix crash when osc completion fails

- openstack_cli/src/catalog/show.rs
- openstack_sdk/src/catalog.rs
- openstack_sdk/src/types/identity/v3.rs
Technically it is possible that the service name in the catalog is
empty as well as region_id of the endpoint. Make it this way so that we
do not fail (should never happen on real clouds but present in dev
situations).
> fix: Make catalog more permissive

- openstack_cli/README.md
- openstack_cli/src/lib.rs
- openstack_sdk/src/auth/auth_helper.rs
- openstack_sdk/src/auth/authtoken.rs
- openstack_sdk/src/auth/v3applicationcredential.rs
- openstack_sdk/src/auth/v3oidcaccesstoken.rs
- openstack_sdk/src/auth/v3password.rs
- openstack_sdk/src/auth/v3token.rs
- openstack_sdk/src/auth/v3totp.rs
- openstack_tui/src/cloud_worker.rs
Use the CloudConfig.name as the connection name in the AuthHelper. This
requires sometimes passing additional parameter into the function, but
makes AuthHelper actually thread safe.
> feat: Drop connection_name from the AuthHelper

- openstack_cli/README.md
- openstack_cli/src/cli.rs
- openstack_cli/src/lib.rs
- openstack_cli/src/output.rs
- openstack_sdk/src/auth/auth_helper.rs
- openstack_sdk/src/auth/authtoken.rs
- openstack_sdk/src/auth/v3applicationcredential.rs
- openstack_sdk/src/auth/v3oidcaccesstoken.rs
- openstack_sdk/src/auth/v3password.rs
- openstack_sdk/src/auth/v3token.rs
- openstack_sdk/src/auth/v3totp.rs
- openstack_sdk/src/openstack.rs
- openstack_sdk/src/openstack_async.rs
Users might want to provide alternative ways of handling secrets of
cloud connections (i.e. pass, encrypted file, bitwarden, etc). Enable
them use own managed wrappers to extract secrets with `osc` invoking
such executable passing attribute and connection name that the `osc` is
currently trying to connect to.
> feat: Add `--auth-helper-cmd` for external AuthHelper

- openstack_cli/src/dns/v2/blacklist/list.rs
- openstack_cli/src/dns/v2/pool/list.rs
- openstack_cli/src/dns/v2/quota/set.rs
- openstack_cli/src/dns/v2/service_status/list.rs
- openstack_cli/src/dns/v2/tld/list.rs
- openstack_cli/src/dns/v2/tsigkey/list.rs
- openstack_cli/src/dns/v2/zone/task/export/list.rs
- openstack_cli/src/dns/v2/zone/task/import/list.rs
- openstack_cli/src/dns/v2/zone/task/transfer_accept/list.rs
- openstack_cli/src/dns/v2/zone/task/transfer_request/list.rs
- openstack_sdk/src/api/dns/v2/blacklist/list.rs
- openstack_sdk/src/api/dns/v2/limit/get.rs
- openstack_sdk/src/api/dns/v2/pool/list.rs
- openstack_sdk/src/api/dns/v2/quota/set.rs
- openstack_sdk/src/api/dns/v2/service_status/list.rs
- openstack_sdk/src/api/dns/v2/tld/list.rs
- openstack_sdk/src/api/dns/v2/tsigkey/list.rs
- openstack_sdk/src/api/dns/v2/zone/task/export/list.rs
- openstack_sdk/src/api/dns/v2/zone/task/import/list.rs
- openstack_sdk/src/api/dns/v2/zone/task/transfer_accept/list.rs
- openstack_sdk/src/api/dns/v2/zone/task/transfer_request/list.rs
- openstack_types/data/dns/v2.1.yaml
- openstack_types/data/dns/v2.yaml
- openstack_types/src/dns/v2/quota/response/get.rs
- openstack_types/src/dns/v2/quota/response/set.rs
All dns list/get operations support `x-auth-all-projects` and
`x-auth-sudo-project-id` headers, which can be used by admins.
Change-Id: Ic5a7cd6c0312a6ac28d895c290924621943e598a
Changes are triggered by https://review.opendev.org/955289
> feat: Add header query params to dns list operations

- .github/workflows/release.yml
- dist-workspace.toml
Update the version of the cargo-dist (at least it looks now better than it was few month ago). In addition to that start building also linux and windows arm artifacts (useful i.e. when running inside the VMs).
> chore: Update cargo-dist version

- openstack_cli/src/common.rs
Use split_once for safer and simpler key=value parsing
> refactor: Simplify parse_key_val_opt and parse_key_val
